on: push
name: Jenkins single-shot master
jobs:
  jenkinsfile-runner-prepackaged:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Install Yarn
        run: npm install -g yarn

      # Install dependencies inside the 'client-app' folder
      - name: Install dependencies
        run: yarn install
        working-directory: ./client-app  # Specifies the folder where yarn.lock is located

      - name: Jenkinsfile Runner Prepackaged
        uses: jenkinsci/jenkinsfile-runner-github-actions@v0.2
