name: Jenkins single-shot master

on: push

jobs:
  jenkinsfile-runner-prepackaged:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      # Navigate to the client-app directory
      - name: Navigate to client-app folder
        working-directory: ./client-app
        run: |
          echo "Current directory: $(pwd)"
          ls -la

      # Install dependencies with Yarn
      - name: Install dependencies
        working-directory: ./client-app
        run: |
          yarn install --frozen-lockfile

      # Run Jenkinsfile Runner
      - name: Jenkinsfile Runner Prepackaged
        uses: jenkinsci/jenkinsfile-runner-github-actions@v0.2
        # Specify any inputs if required by the action