on: push
name: Jenkins single-shot master
jobs:
  jenkinsfile-runner-prepackaged:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      # Navigate to the client-app folder where the yarn.lock file exists
      - name: Navigate to client-app folder
        working-directory: ./client-app
        run: |
          ls -la  # To verify that we are inside the correct directory

      # Install dependencies inside the 'client-app' folder
      - name: Install dependencies
        working-directory: ./client-app
        run: yarn install  # Make sure to run this in the correct folder

      - name: Jenkinsfile Runner Prepackaged
        uses: jenkinsci/jenkinsfile-runner-github-actions@v0.2
